version: '3.1'

services:

  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./ghost-data:/var/lib/ghost/content
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: supersecret
      database__connection__database: ghost
      NODE_ENV: development
    command: >
      bash -c "cp config.production.json config.development.json && bash /usr/local/bin/docker-entrypoint.sh node current/index.js"

  db:
    image: mysql:5.7
    restart: always
    # ports:
      # - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret